<?php
/**
 * @file
 *
 *
 *
 * @author Attila Fekete - http://drupal.org/user/762986
 */

define('SOUNDCLOUDFIELD_DEFAULT_WIDTH', 100);
define('SOUNDCLOUDFIELD_DEFAULT_HEIGHT', 81);
define('SOUNDCLOUDFIELD_DEFAULT_SET_HEIGHT', 305);

/**
 * Implements hook_field_info().
 */
function soundcloudfield_field_info() {
  return array(
    'soundcloud' => array(
      'label' => t('SoundCloud'),
      'description' => t('This field stores a SoundCloud track or set URL.'),
      'instance_settings' => array(
        'width'         => SOUNDCLOUDFIELD_DEFAULT_WIDTH,
        'height'        => SOUNDCLOUDFIELD_DEFAULT_HEIGHT,
        'set_height'    => SOUNDCLOUDFIELD_DEFAULT_SET_HEIGHT,
        'autoplay'      => FALSE,
        'showcomments'  => FALSE,
        'showplaycount' => FALSE,
        'showartwork'   => FALSE,
        'color'         => 'ff7700',
      ),
      'default_widget'    => 'soundcloud_url',
      'default_formatter' => 'soundcloud_default',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 * Pseudo-hook.
 */
// function soundcloudfield_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
function soundcloudfield_field_validate($obj_type, $object, $field, $instance, $langcode, &$items, &$errors) {
  if ($field['type'] == 'soundcloud') {
    foreach ($items as $delta => $item) {
      if (!empty($item['url']) && !preg_match('@^http://soundcloud\.com/([^"\&]+)@i', $item['url'], $matches)) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error'   => 'soundcloudfield_invalid_url',
          'message' => t('%url is not a valid SoundCloud URL.', array('%url' => $item['url'])),
        );
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 *
 * Pseudo-hook.
 */
function soundcloudfield_field_is_empty($item, $field) {
  if ($field['type'] == 'soundcloud') {
    if (empty($item['url'])) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_field_settings_form().
 *
 * Pseudo-hook.
 */
function soundcloudfield_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];

  if ($field['type'] == 'soundcloud') {
    $form = array(
      '#element_validate' => array('soundcloudfield_settings_form_validate'),
    );
    $form['player'] = array(
      '#type'         => 'fieldset',
      '#title'        => t('SoundCloud settings'),
      '#collapsible'  => TRUE,
      '#collapsed'    => FALSE,
    );
    $form['player']['width'] = array(
      '#type'             => 'textfield',
      '#title'            => t('Width'),
      '#size'             => 4,
      '#default_value'    => empty($settings['player']['width']) ? SOUNDCLOUDFIELD_DEFAULT_WIDTH : $settings['player']['width'],
      '#description'      => t('Player width in percent. Default is @width.', array('@width' => SOUNDCLOUDFIELD_DEFAULT_WIDTH)),
      '#required'         => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['player']['height'] = array(
      '#type'             => 'textfield',
      '#title'            => t('Height for tracks'),
      '#size'             => 4,
      '#default_value'    => empty($settings['player']['height']) ? SOUNDCLOUDFIELD_DEFAULT_HEIGHT : $settings['player']['height'],
      '#description'      => t('Player height for tracks. Default is @height.', array('@height' => SOUNDCLOUDFIELD_DEFAULT_HEIGHT)),
      '#required'         => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['player']['set_height'] = array(
      '#type'             => 'textfield',
      '#title'            => t('Height for sets'),
      '#size'             => 4,
      '#default_value'    => empty($settings['player']['set_height']) ? SOUNDCLOUDFIELD_DEFAULT_SET_HEIGHT : $settings['player']['set_height'],
      '#description'      => t('Player height for sets. Default is @height.', array('@height' => SOUNDCLOUDFIELD_DEFAULT_SET_HEIGHT)),
      '#required'         => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['player']['showcomments'] = array(
      '#type'           => 'checkbox',
      '#title'          => t('Show comments'),
      '#default_value'  => empty($settings['player']['showcomments']) ? FALSE : $settings['player']['showcomments'],
      '#description'    => t('Show comments in player'),
    );
    $form['player']['autoplay'] = array(
      '#type'           => 'checkbox',
      '#title'          => t('Autoplay'),
      '#default_value'  => empty($settings['player']['autoplay']) ? FALSE : $settings['player']['autoplay'],
      '#description'    => t('Player autoplay'),
    );
    $form['player']['showplaycount'] = array(
      '#type'           => 'checkbox',
      '#title'          => t('Show play count'),
      '#default_value'  => empty($settings['player']['showplaycount']) ? FALSE : $settings['player']['showplaycount'],
      '#description'    => t('Show play count in player'),
    );
    $form['player']['showartwork'] = array(
      '#type'           => 'checkbox',
      '#title'          => t('Show artwork'),
      '#default_value'  => empty($settings['player']['showartwork']) ? FALSE : $settings['player']['showartwork'],
      '#description'    => t('Show artwork in player'),
    );
    $form['player']['color'] = array(
      '#type'           => module_exists('jquery_colorpicker') ? 'jquery_colorpicker' : 'textfield',
      '#title'          => t('Player color'),
      '#default_value'  => empty($settings['player']['color']) ? 'ff7700' : $settings['player']['color'],
      '#required'       => TRUE,
      '#description'    => t('Player color in hexadecimal format. Default is ff7700. Turn on the jQuery Colorpicker module if available.'),
    );
  }

  return $form;
}

/**
 * Validate the field settings form
 */
function soundcloudfield_settings_form_validate($element, &$form_state, $complete_form) {
  if (!empty($form_state['values']['instance']['settings']['player']['width']) && ($form_state['values']['instance']['settings']['player']['width'] < 1 || $form_state['values']['instance']['settings']['player']['width'] > 100)) {
    form_set_error('instance][settings][player][width', t('Player width must be a positive integer between 1-100'));
  }
}

/**
 * Implements hook_widget_info().
 */
function soundcloudfield_field_widget_info() {
  return array(
    'soundcloud_url' => array(
      'label'       => t('SoundCloud URL'),
      'field types' => array('soundcloud'),
      'behaviors'   => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value'   => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 * Pseudo-hook.
 */
function soundcloudfield_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $base = $element;

  if ($instance['widget']['type'] == 'soundcloud_url') {
    $element['url'] = array(
      '#type'           => 'textfield',
      '#default_value'  => isset($items[$delta]['url']) ? $items[$delta]['url'] : NULL,
    ) + $base;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_info().
 */
function soundcloudfield_field_formatter_info() {
  return array(
    'soundcloud_default' => array(
      'label'       => t('Flash player'),
      'field types' => array('soundcloud'),
    ),
    'soundcloud_html5' => array(
      'label'       => t('HTML5 player'),
      'field types' => array('soundcloud'),
    ),
    'soundcloud_link' => array(
      'label'       => t('Link'),
      'field types' => array('soundcloud'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function soundcloudfield_field_formatter_view($obj_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $instance['settings']['player'];

  $showcomments = ($settings['showcomments']) ? 'true' : 'false';
  $autoplay = ($settings['autoplay']) ? 'true' : 'false';
  $showplaycount = ($settings['showplaycount']) ? 'true' : 'false';
  $showartwork = ($settings['showartwork']) ? 'true' : 'false';
  $color = $settings['color'];

  switch ($display['type']) {

    case 'soundcloud_default':
      foreach ($items as $delta => $item) {
        $output = '';
        $encoded_url = urlencode($item['url']);
        $parsed_url = parse_url($item['url']);

        $splitted_url = explode("/", $parsed_url['path']);

        if ($splitted_url[2] != 'sets') {
          $height = $settings['height'];
          $params = 'url=' . $encoded_url .
                    '&amp;show_comments=' . $showcomments .
                    '&amp;auto_play=' . $autoplay .
                    '&amp;color=' . $color;
        }
        else {
          $height = $settings['set_height'];
          $params = 'url=' . $encoded_url .
                    '&amp;show_comments=' . $showcomments .
                    '&amp;auto_play=' . $autoplay .
                    '&amp;show_playcount=' . $showplaycount .
                    '&amp;show_artwork=' . $showartwork .
                    '&amp;color=' . $color;
        }

        $output = '<object height="' . $height . '" width="' . $settings['width'] . '%"><param name="movie" value="https://player.' . $parsed_url['host'] . '/player.swf?' . $params . '"></param>';
        $output .= '<param name="allowscriptaccess" value="always"></param><embed allowscriptaccess="always" height="' . $height . '" src="https://player.' . $parsed_url['host'] . '/player.swf?' . $params . '" type="application/x-shockwave-flash" width="' . $settings['width'] . '%"></embed></object>';

        $element[$delta] = array('#markup' => $output);
      }
      break;

    case 'soundcloud_html5':
      $oembed_endpoint = 'http://soundcloud.com/oembed';

      foreach ($items as $delta => $item) {
        $output = '';
        $encoded_url = urlencode($item['url']);

        // Create the URL
        $oembed_url = $oembed_endpoint . '?iframe=true&url=' . ($encoded_url);

        // Load in the oEmbed XML
        $oembed = simplexml_load_string(soundcloudfield_curl_get($oembed_url));

        // Replace player default settings with our settings
        $final_iframe = preg_replace('/(width=)"([^"]+)"/', 'width="' . $settings['width'] . '%"', $oembed->html);

        if (preg_match('/auto_play=(true|false)/', $final_iframe)) {
          $final_iframe = preg_replace('/auto_play=(true|false)/', 'auto_play=' . $autoplay, $final_iframe);
        }
        else {
          $final_iframe = preg_replace('/">/', '&auto_play=' . $autoplay . '">', $final_iframe);
        }

        if (preg_match('/show_artwork=(true|false)/', $final_iframe)) {
          $final_iframe = preg_replace('/show_artwork=(true|false)/', 'show_artwork=' . $showartwork, $final_iframe);
        }
        else {
          $final_iframe = preg_replace('/">/', '&show_artwork=' . $showartwork . '">', $final_iframe);
        }

        if (preg_match('/color=([a-zA-Z0-9]{6})/', $final_iframe)) {
          $final_iframe = preg_replace('/color=([a-zA-Z0-9]{6})/', 'color=' . $color, $final_iframe);
        }
        else {
          $final_iframe = preg_replace('/">/', '&color=' . $color . '">', $final_iframe);
        }

        $output = html_entity_decode($final_iframe);  // '$oembed->html' for original embed

        $element[$delta] = array('#markup' => $output);
      }
      break;

    case 'soundcloud_link':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => l($item['url'], $item['url']));
      }
      break;
  }

  return $element;
}

/**
 * Implement hook_field_error().
 */
function soundcloudfield_field_widget_error($element, $error) {
  switch ($error['error']) {
    case 'soundcloudfield_invalid_url':
      form_error($element, $error['message']);
      break;
  }
}

/*
 * Curl helper function
 */
function soundcloudfield_curl_get($url) {
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
    $return = curl_exec($curl);
    curl_close($curl);
    return $return;
}
